spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
aws.eventBridge.bus=default-event-bus
aws.s3.bucket=mon-bucket-de-test